### ISSUE TITLE
503 Error

### ISSUE THREAD

**Issue by xianti** [galengidman/go-redirects#1]
Getting this error on all redirects right now:

Error 503 Service Unavailable

Service Unavailable

Guru Meditation:

XID: 1219727479

Varnish cache server

**Comment by galengidman** [comment]
Some googling turned up this article — http://www.technoreply.com/solving-dreaded-varnish-503-error/

Not sure if there's something there that can help. Debugging Varnish is definitely something that's out of my expertise.

**Comment by xianti** [comment]
Thanks, Galen.

But I have no idea what any of this is or means. I am not a developer. I thought the plugin developer is supposed to fix this.

Media Cookery

Marketing + Design

Be a big brand. We'll help you get there.

+1 310 968 5966

 http://mediacookery.com/ mediacookery.com

 https://www.facebook.com/MediaCookery    http://instagram.com/mediacookery    https://twitter.com/MediaCookery    https://plus.google.com/+MediaCookery

**Comment by galengidman** [comment]
As the developer of the plugin, it's my intention to fix issues as they arise with this plugin. However, based on my research, this error is a very general error produced by Varnish, which is caching software designed to speed up your web application. This error provides no actual information about what the issue is — it just says there is one — somewhere/somehow.

Without and exact copy of your hosting environment, I would not be able to debug this, and honestly, with my lack of Varnish experience, I might not be able to then either.

I wish I could help you further with this, but there's not much I can do. I'm sorry for an inconvenience this has caused.

**Comment by xianti** [comment]
Oh, I got it. I disabled the Varnish Cache on our host’s server. Never should’ve been turned on in the first place, as we are caching via WordPress. That fixed the problem.

Thanks.

Media Cookery

Marketing + Design

Be a big brand. We'll help you get there.

+1 310 968 5966

 http://mediacookery.com/ mediacookery.com

 https://www.facebook.com/MediaCookery    http://instagram.com/mediacookery    https://twitter.com/MediaCookery    https://plus.google.com/+MediaCookery

**Comment by galengidman** [comment]
Perfect 🎉
